USE TNTECH_VEHICLE_MANGEMENT_SYSTEM
GO

-- 공통코드 조회
CREATE OR ALTER PROCEDURE SP_GET_COMMON_CODE
    @GROUP_CODE NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        CONTENT_CODE, 
        CODE_NAME
    FROM TB_COMMONCODE
    WHERE GROUP_CODE = @GROUP_CODE
    ORDER BY SORT_ORDER ASC;
END
GO

-- 공통코드 전체 조회
CREATE OR ALTER PROCEDURE SP_GET_ALL_COMMON_CODES
AS
BEGIN
    SET NOCOUNT ON;
    SELECT 
        GROUP_CODE,
        CONTENT_CODE,
        CODE_NAME,
        SORT_ORDER
    FROM TB_COMMONCODE
    ORDER BY GROUP_CODE, SORT_ORDER ASC;
END
GO

-- 공통코드 등록
CREATE OR ALTER PROCEDURE SP_REGISTER_COMMON_CODE
    @GROUP_CODE     NVARCHAR(50),
    @CONTENT_CODE   NVARCHAR(20),
    @CODE_NAME      NVARCHAR(100),
    @SORT_ORDER     INT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM TB_COMMONCODE WHERE GROUP_CODE = @GROUP_CODE AND CONTENT_CODE = @CONTENT_CODE)
    BEGIN
        SELECT 0 AS SUCCESS, '이미 존재하는 코드입니다.' AS MSG;
        RETURN;
    END

    INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER)
    VALUES (@GROUP_CODE, @CONTENT_CODE, @CODE_NAME, @SORT_ORDER);

    SELECT 1 AS SUCCESS, '코드 등록 완료' AS MSG;
END
Go

-- 공통코드 수정
CREATE OR ALTER PROCEDURE SP_UPDATE_COMMON_CODE
    @GROUP_CODE     NVARCHAR(50),
    @CONTENT_CODE   NVARCHAR(20),
    @CODE_NAME      NVARCHAR(100),
    @SORT_ORDER     INT
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE TB_COMMONCODE
    SET CODE_NAME = @CODE_NAME,
        SORT_ORDER = @SORT_ORDER
    WHERE GROUP_CODE = @GROUP_CODE AND CONTENT_CODE = @CONTENT_CODE;

    SELECT 1 AS SUCCESS, '코드 수정 완료' AS MSG;
END
GO

-- 공통코드 삭제
CREATE OR ALTER PROCEDURE SP_DELETE_COMMON_CODE
    @GROUP_CODE     NVARCHAR(50),
    @CONTENT_CODE   NVARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM TB_COMMONCODE 
    WHERE GROUP_CODE = @GROUP_CODE AND CONTENT_CODE = @CONTENT_CODE;

    SELECT 1 AS SUCCESS, '코드 삭제 완료' AS MSG;
END
GO

USE TNTECH_VEHICLE_MANGEMENT_SYSTEM
GO

-- 1. 그룹코드 전체 조회
CREATE OR ALTER PROCEDURE SP_GET_ALL_GROUP_CODES
AS
BEGIN
    SET NOCOUNT ON;
    
    SELECT 
        GROUP_CODE,
        GROUP_NAME,
        DESCRIPTION
    FROM TB_GROUPCODE
    ORDER BY GROUP_CODE ASC;
END
GO

-- 2. 그룹코드 등록
CREATE OR ALTER PROCEDURE SP_REGISTER_GROUP_CODE
    @GROUP_CODE     NVARCHAR(50),
    @GROUP_NAME     NVARCHAR(100),
    @DESCRIPTION    NVARCHAR(200)
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM TB_GROUPCODE WHERE GROUP_CODE = @GROUP_CODE)
    BEGIN
        SELECT 0 AS SUCCESS, '이미 존재하는 그룹코드입니다.' AS MSG;
        RETURN;
    END

    INSERT INTO TB_GROUPCODE (GROUP_CODE, GROUP_NAME, DESCRIPTION)
    VALUES (@GROUP_CODE, @GROUP_NAME, @DESCRIPTION);

    SELECT 1 AS SUCCESS, '그룹코드 등록 완료' AS MSG;
END
GO

-- 3. 그룹코드 수정
CREATE OR ALTER PROCEDURE SP_UPDATE_GROUP_CODE
    @GROUP_CODE     NVARCHAR(50),
    @GROUP_NAME     NVARCHAR(100),
    @DESCRIPTION    NVARCHAR(200)
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE TB_GROUPCODE
    SET GROUP_NAME = @GROUP_NAME,
        DESCRIPTION = @DESCRIPTION
    WHERE GROUP_CODE = @GROUP_CODE;

    SELECT 1 AS SUCCESS, '그룹코드 수정 완료' AS MSG;
END
GO

-- 4. 그룹코드 삭제
-- (주의: TB_COMMONCODE 테이블 생성 시 ON DELETE CASCADE를 걸어두었다면, 
--  해당 그룹코드를 지울 때 하위 공통코드도 함께 지워집니다.)
CREATE OR ALTER PROCEDURE SP_DELETE_GROUP_CODE
    @GROUP_CODE     NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM TB_GROUPCODE 
    WHERE GROUP_CODE = @GROUP_CODE;

    SELECT 1 AS SUCCESS, '그룹코드 삭제 완료' AS MSG;
END
GO