USE TNTECH_VEHICLE_MANGEMENT_SYSTEM
GO

-- 로그인 프로시저 (SP_LOGIN_MEMBER)
CREATE OR ALTER PROCEDURE SP_LOGIN_MEMBER
    @MEMBER_ID NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        MEMBER_ID, 
        MEMBER_NAME, 
        DEPARTMENT, 
        MEMBER_PASSWORD,
        MEMBER_ROLE
    FROM TB_MEMBERS
    WHERE MEMBER_ID = @MEMBER_ID
END
GO

-- 회원가입 프로시저
CREATE OR ALTER PROCEDURE SP_REGISTER_MEMBER
    @MEMBER_ID       NVARCHAR(50),
    @MEMBER_NAME     NVARCHAR(50),
    @DEPARTMENT      NVARCHAR(50),
    @MEMBER_PASSWORD NVARCHAR(MAX),
    @MEMBER_ROLE     NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    -- 중복 아이디 체크
    IF EXISTS (SELECT 1 FROM TB_MEMBERS WHERE MEMBER_ID = @MEMBER_ID)
    BEGIN
        SELECT 0 AS SUCCESS, '이미 존재하는 아이디입니다.' AS MSG;
        RETURN;
    END

    -- 저장 (INSERT)
    INSERT INTO TB_MEMBERS (MEMBER_ID, MEMBER_NAME, DEPARTMENT, MEMBER_PASSWORD, MEMBER_ROLE)
    VALUES (@MEMBER_ID, @MEMBER_NAME, @DEPARTMENT, @MEMBER_PASSWORD, @MEMBER_ROLE);

    SELECT 1 AS SUCCESS, '회원가입 성공' AS MSG;
END
GO


