/**
 * @file        Create_Procedure_CommonCode.sql
 * @description 그룹 코드 및 상세 공통 코드의 CRUD 프로시저 정의
 */

USE TNTECH_VEHICLE_MANGEMENT_SYSTEM
GO

/**
 * [특정 그룹의 공통 코드 조회]
 * @param @GROUP_CODE - 조회할 그룹 식별자
 * 설명: UI 콤보박스 등에 사용될 특정 그룹의 상세 코드와 명칭 목록 반환
 */
CREATE OR ALTER PROCEDURE SP_GET_COMMON_CODE
    @GROUP_CODE NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        CONTENT_CODE, 
        CODE_NAME
    FROM TB_COMMONCODE
    WHERE GROUP_CODE = @GROUP_CODE
    ORDER BY SORT_ORDER ASC;
END
GO

/**
 * [공통 코드 전체 조회]
 * 설명: 시스템에 등록된 모든 상세 코드 목록을 그룹 및 정렬 순서대로 반환
 */
CREATE OR ALTER PROCEDURE SP_GET_ALL_COMMON_CODES
AS
BEGIN
    SET NOCOUNT ON;
    SELECT 
        GROUP_CODE,
        CONTENT_CODE,
        CODE_NAME,
        SORT_ORDER
    FROM TB_COMMONCODE
    ORDER BY GROUP_CODE, SORT_ORDER ASC;
END
GO

/**
 * [신규 공통 코드 등록]
 * @param @GROUP_CODE   - 대상 그룹 코드
 * @param @CONTENT_CODE - 신규 상세 코드
 * @param @CODE_NAME    - 코드 명칭
 * @param @SORT_ORDER   - 표시 순서
 * 설명: 그룹 내 동일 코드 존재 여부 확인 후 데이터 삽입
 */
CREATE OR ALTER PROCEDURE SP_REGISTER_COMMON_CODE
    @GROUP_CODE     NVARCHAR(50),
    @CONTENT_CODE   NVARCHAR(20),
    @CODE_NAME      NVARCHAR(100),
    @SORT_ORDER     INT
AS
BEGIN
    SET NOCOUNT ON;

    -- 코드 중복 체크
    IF EXISTS (SELECT 1 FROM TB_COMMONCODE WHERE GROUP_CODE = @GROUP_CODE AND CONTENT_CODE = @CONTENT_CODE)
    BEGIN
        SELECT 0 AS SUCCESS, '이미 존재하는 코드입니다.' AS MSG;
        RETURN;
    END

    INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER)
    VALUES (@GROUP_CODE, @CONTENT_CODE, @CODE_NAME, @SORT_ORDER);

    SELECT 1 AS SUCCESS, '코드 등록 완료' AS MSG;
END
Go

/**
 * [공통 코드 정보 수정]
 * 설명: 그룹 및 상세 코드를 기준으로 명칭과 정렬 순서 업데이트
 */
CREATE OR ALTER PROCEDURE SP_UPDATE_COMMON_CODE
    @GROUP_CODE     NVARCHAR(50),
    @CONTENT_CODE   NVARCHAR(20),
    @CODE_NAME      NVARCHAR(100),
    @SORT_ORDER     INT
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE TB_COMMONCODE
    SET CODE_NAME = @CODE_NAME,
        SORT_ORDER = @SORT_ORDER
    WHERE GROUP_CODE = @GROUP_CODE AND CONTENT_CODE = @CONTENT_CODE;

    SELECT 1 AS SUCCESS, '코드 수정 완료' AS MSG;
END
GO

/**
 * [공통 코드 삭제]
 * 설명: 그룹 및 상세 코드를 기준으로 데이터 삭제
 */
CREATE OR ALTER PROCEDURE SP_DELETE_COMMON_CODE
    @GROUP_CODE     NVARCHAR(50),
    @CONTENT_CODE   NVARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM TB_COMMONCODE 
    WHERE GROUP_CODE = @GROUP_CODE AND CONTENT_CODE = @CONTENT_CODE;

    SELECT 1 AS SUCCESS, '코드 삭제 완료' AS MSG;
END
GO

-- --- 그룹 코드 관리 영역 ---

/**
 * [그룹 코드 전체 조회]
 * 설명: 상세 코드의 상위 분류인 그룹 코드 전체 목록 반환
 */
CREATE OR ALTER PROCEDURE SP_GET_ALL_GROUP_CODES
AS
BEGIN
    SET NOCOUNT ON;
    
    SELECT 
        GROUP_CODE,
        GROUP_NAME,
        DESCRIPTION
    FROM TB_GROUPCODE
    ORDER BY GROUP_CODE ASC;
END
GO

/**
 * [신규 그룹 코드 등록]
 * @param @GROUP_CODE  - 그룹 식별 코드
 * @param @GROUP_NAME  - 그룹 명칭
 * @param @DESCRIPTION - 상세 설명
 * 설명: 그룹 코드 중복 여부 확인 후 신규 카테고리 생성
 */
CREATE OR ALTER PROCEDURE SP_REGISTER_GROUP_CODE
    @GROUP_CODE     NVARCHAR(50),
    @GROUP_NAME     NVARCHAR(100),
    @DESCRIPTION    NVARCHAR(200)
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM TB_GROUPCODE WHERE GROUP_CODE = @GROUP_CODE)
    BEGIN
        SELECT 0 AS SUCCESS, '이미 존재하는 그룹코드입니다.' AS MSG;
        RETURN;
    END

    INSERT INTO TB_GROUPCODE (GROUP_CODE, GROUP_NAME, DESCRIPTION)
    VALUES (@GROUP_CODE, @GROUP_NAME, @DESCRIPTION);

    SELECT 1 AS SUCCESS, '그룹코드 등록 완료' AS MSG;
END
GO

/**
 * [그룹 코드 정보 수정]
 * 설명: 그룹 코드를 식별자로 하여 그룹명 및 설명 업데이트
 */
CREATE OR ALTER PROCEDURE SP_UPDATE_GROUP_CODE
    @GROUP_CODE     NVARCHAR(50),
    @GROUP_NAME     NVARCHAR(100),
    @DESCRIPTION    NVARCHAR(200)
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE TB_GROUPCODE
    SET GROUP_NAME = @GROUP_NAME,
        DESCRIPTION = @DESCRIPTION
    WHERE GROUP_CODE = @GROUP_CODE;

    SELECT 1 AS SUCCESS, '그룹코드 수정 완료' AS MSG;
END
GO

/**
 * [그룹 코드 삭제]
 * 설명: 그룹 코드 삭제 처리
 */
CREATE OR ALTER PROCEDURE SP_DELETE_GROUP_CODE
    @GROUP_CODE     NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM TB_GROUPCODE 
    WHERE GROUP_CODE = @GROUP_CODE;

    SELECT 1 AS SUCCESS, '그룹코드 삭제 완료' AS MSG;
END
GO