USE TNTECH_VEHICLE_MANGEMENT_SYSTEM
GO

-- =================================================================
-- 1. 기존 데이터 초기화 (초기화가 필요할 때만 주석 해제 후 사용)
-- =================================================================
-- DELETE FROM TB_COMMONCODE;
-- DELETE FROM TB_GROUPCODE;
-- GO

-- =================================================================
-- 2. 그룹 코드 (TB_GROUPCODE) 데이터 세팅 (부모 테이블)
-- =================================================================
INSERT INTO TB_GROUPCODE (GROUP_CODE, GROUP_NAME, DESCRIPTION) VALUES ('차량상태', '차량상태', '차량의 현재 상태');
INSERT INTO TB_GROUPCODE (GROUP_CODE, GROUP_NAME, DESCRIPTION) VALUES ('대여구분', '대여구분', '배차 신청 시간 단위');
INSERT INTO TB_GROUPCODE (GROUP_CODE, GROUP_NAME, DESCRIPTION) VALUES ('업무구분', '업무구분', '배차 신청 시 목적');
INSERT INTO TB_GROUPCODE (GROUP_CODE, GROUP_NAME, DESCRIPTION) VALUES ('직급', '직급', '임직원 직급 및 권한 설정');
INSERT INTO TB_GROUPCODE (GROUP_CODE, GROUP_NAME, DESCRIPTION) VALUES ('부서', '부서', '임직원 소속 부서');
INSERT INTO TB_GROUPCODE (GROUP_CODE, GROUP_NAME, DESCRIPTION) VALUES ('점검내용', '점검내용', '차량 점검 및 수리 항목');
GO

-- =================================================================
-- 3. 공통 코드 (TB_COMMONCODE) 데이터 세팅 (자식 테이블)
-- =================================================================
-- 차량상태 (VehiclePage.jsx)
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('차량상태', 'AVAILABLE', '대여 가능', 1);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('차량상태', 'IN_USE', '운행 중', 2);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('차량상태', 'REPAIR', '정비 중', 3);

-- 대여구분 (DispatchRequestPage.jsx)
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('대여구분', 'ALL', '종일', 1);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('대여구분', 'AM', '오전', 2);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('대여구분', 'PM', '오후', 3);

-- 업무구분 (DispatchRequestPage.jsx)
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('업무구분', 'BUSINESS_CONSULTATION', '업무협의', 1);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('업무구분', 'FIELD_INSTALLATION', '현장설치', 2);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('업무구분', 'DELIVERY', '납품', 3);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('업무구분', 'ETC', '기타', 4);

-- 직급 (MemberPage.jsx 및 Sidebar 권한)
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('직급', 'CHIEF_EXECUTIVE_OFFICER', '대표', 1);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('직급', 'GENERAL_MANAGER', '본부장', 2);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('직급', 'DIRECTOR', '이사', 3);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('직급', 'TEAM_LEADER', '팀장', 4);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('직급', 'PROFESSIONAL', '프로', 5);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('직급', 'ADMINISTRATOR', '관리자', 6);

-- 부서 (MemberPage.jsx)
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('부서', 'TNTECH', '티앤테크', 1);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('부서', 'MANAGEMENT_SUPPORT_TEAM', '경영지원팀', 2);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('부서', 'TECHNICAL_SALES_SEOUL', '기술영업팀_서울지사', 3);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('부서', 'TECHNICAL_SALES_TEAM_01', '기술영업팀_1팀', 4);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('부서', 'TECHNICAL_SALES_TEAM_02', '기술영업팀_2팀', 5);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('부서', 'RESEARCH_DEVELOPMENT_CENTER', '기업부설연구소', 6);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('부서', 'SOLUTION_DEVELOPMENT_TEAM_01', '솔루션개발_1팀', 7);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('부서', 'SOLUTION_DEVELOPMENT_TEAM_02', '솔루션개발_2팀', 8);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('부서', 'ADMINISTRATOR', '관리자', 9);

-- 점검내용
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('점검내용', 'WASH', '세차', 1);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('점검내용', 'PARTS_REPLACEMENT', '소모품교환', 2);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('점검내용', 'REPAIR', '수리', 3);
INSERT INTO TB_COMMONCODE (GROUP_CODE, CONTENT_CODE, CODE_NAME, SORT_ORDER) VALUES ('점검내용', 'INSPECTION', '점검', 4);
GO